### ISSUE TITLE
Wildcard and regular expressions only work with letters, not numbers.

### ISSUE THREAD

**Issue by fluffyparakeet** [otacke/h5p-essay#31]
When attempting to use a serial number with random numbers at the end of a fixed string as a keyword, neither the wildcard * or regex / are compatible with numbers preceding or following a search term. For example, if I attempted to use *MM71.098.B* as a term, the value MM71.098.BCD would be valid, but MM71.098.B99 would not.

**Comment by fluffyparakeet** [comment]
This is what I see in the development console:
![br4](https://user-images.githubusercontent.com/26904571/39461702-4538f09c-4cd2-11e8-830c-e272a86941b4.png)

**Comment by otacke** [comment]
So far, so good! Some messages might pop up in the lower right box as you browse the web, just keep it open. Does anything appear when you click the check button of your Essay content?

**Comment by fluffyparakeet** [comment]
This is what I see when I click the check button:
![br6](https://user-images.githubusercontent.com/26904571/39481105-eb4df2f4-4d2f-11e8-801d-044bd584d8e5.png)

**Comment by otacke** [comment]
Okay, no error messages.

Are you using the latest development version here from github (that's what I assumed) or did you use the latest official version that's provided by the H5P hub? The latter doesn't have the regexp feature yet.

**Comment by fluffyparakeet** [comment]
That explains the issue - thank you for your help! I was using the version available through the hub. Now I have an additional question - when attempting to upload and use version 1.1.2 I get these error messages:
![validatingh5pfailed](https://user-images.githubusercontent.com/26904571/39485090-5b09205c-4d3d-11e8-9af2-4fdb21506200.png)

What should I do to resolve them and use the newer version?

**Comment by otacke** [comment]
If you're trying to upload libraries, you'll have to do that on the library page of H5P, not in the content type hub (which is for content). However, since you're using WordPress, it's a little more tedious to use development versions.

The easiest and future-update-friendliest way probably is to replace the files in wp-content/uploads/h5p/libraries/h5p-essay with their counterparts in the archive that you downloaded and then delete the files in wp-content/uploads/h5p/cachedassets. You might need to do the same with [h5p-text-utilities](https://github.com/otacke/h5p-text-utilities), and you might need to refresh your browser's cache (shift+F5).

In any case: You should not do this on a productive system if you're not sure what you're doing. Be sure to make a backup first.

Alternatively, just wait until one of my colleagues has finished the peer-review. There should be an official update shortly that you can download normally using the H5P content hub.

**Comment by fluffyparakeet** [comment]
Thank you for your help! One more question - would it be possible to keep the keywords from being shown to the user in the feedback tab? I'd like to hide the regex and just show the feedback if possible.
![untitled](https://user-images.githubusercontent.com/26904571/39488942-83b7cf06-4d49-11e8-90aa-bf2edcbcbc8a.png)

**Comment by otacke** [comment]
Yes, in the latest version you can set the visibility to "keyword" / "alternative found" / "answer given" / "none" for each keyword group.

What are you actually using Essay for? That doesn't look like an educational scenario.

**Comment by otacke** [comment]
There's no support for regexp flags.

**Comment by fluffyparakeet** [comment]
I'm using it to check the compatibility of serial numbers for different years of Mac laptops with solid state drives that I engineer - it probably seems very random, but your tool was the only one that I could find that had all of the functionality that I needed. Thanks again for answering my barrage of questions - I just subscribed to your Patreon! I really appreciate the help.

**Comment by fluffyparakeet** [comment]
Sorry to bother you again, but where is the option to change the visibility? I can't find it in 1.1.3.

**Comment by otacke** [comment]
Sorry for not being clear: with latest version I meant the latest version here on github which should be out soon. I just created a special version for you that should bring an Essay version 1.1.4 to your system if you upload it via H5P's library page. Old contents will have to be updated via the library page as usual, too, if they should get the new features. Since the next official version of H5P Essay will be 1.2.0, this will not become a problem with version numbers when you want to get the official version again. Let me know if everything works.

[h5p_essay_fluffyparakeet.zip](https://github.com/otacke/h5p-essay/files/1965123/h5p_essay_fluffyparakeet.zip)

And thanks for becoming a patron!!! $5 is huge! 

Also, thanks a lot for sharing your use case! It's always very interesting to see what others use your programs for -- even if you designed them for something completely different :-D

**Comment by fluffyparakeet** [comment]
This works perfectly, thank you so much!!!

**Comment by otacke** [comment]
Great! I'll close this issue then, but feel free to get in touch if you have more questions or suggestions -- the forum at h5p. com is probably a good place, because it's kind of the central hub for Q&As and others could join the conversation more easily, too.

**Comment by fluffyparakeet** [comment]
Is there a way to prevent the check button from showing after the initial submission? When the second check button is pressed, another results box shows up above the main results box and is blank. ![bootromversion2](https://user-images.githubusercontent.com/26904571/39497179-bef7ecc2-4d67-11e8-9fd8-6aa2909a97d8.png)
![bootromversion1](https://user-images.githubusercontent.com/26904571/39497206-eafb3b6c-4d67-11e8-954e-fa777b20773e.png)

**Comment by otacke** [comment]
There is no first and second check button, just one. There's just one, and it has a checkmark in front of the label.

Did you relabel the "Show solution" button to "Check"? That's the one with the eye. It should not show up however if the sample solution text is empty (that's the second box you're seeing).

I am a little puzzled what went wrong here unless you have "Result" as the introduction text of the sample solution and at least a blank in the sample solution text field.

**Comment by fluffyparakeet** [comment]
After clearing out the show solution field and making sure there weren't any blank spaces, everything is working as intended. Thanks again!

**Comment by otacke** [comment]
You're welcome!
