### ISSUE TITLE
Forgive minor mistakes setting

### ISSUE THREAD

**Issue by Jarvil** [otacke/h5p-essay#39]
Hello,

Essay has setting "This will accept minor spelling mistakes (3-9 characters: 1 mistake, more than 9 characters: 2 mistakes)." is only english language supported or what languages are? How it does the checking in f.ex. Moodle H5P?

**Comment by otacke** [comment]
Hi Jarvil!

There are plenty of ways to assert the similarity of two strings. I created the [function _isSimilar_ in the TextUtilities library](https://github.com/otacke/h5p-text-utilities/blob/master/scripts/text-utilities.js#L60-L93). It computes the so called [Damerau-Levenshtein distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) which essentially counts the number of changes (delete a character, add a character, exchange a character, swap two adjacent characters) needed to transform one string into the other - those count is consideres as the number of mistakes. In consequence, the algorithm is not tailored to a particular language but will do the same for any language.

Also, as always, H5P content types are not tailored to a particular host system. It doesn't matter if you use moodle, WordPress, Drupal or something else - they always work the same.

Cheers,
Oliver

**Comment by Jarvil** [comment]
Hello,

So it compares the characters in a keyword and how much they wary. And you will get full points even if you have 9 wrong charcaters so number of mistakes doesn't count

**Comment by otacke** [comment]
Hi Jarvil!

Yes, you are correct. If someone wrote "desoxyribonucliec acid" instead of "deoxyribonucleic acid" this would still count as a valid answer. The correct answer _deoxyribonucleic acid_ has more than 9 characters and there are just two changes needed:
1. Remove the extra _s_
2. Swap _i_ and _e_

In an essay scenario that's "stupidly" based on detection of keywords, it doesn't make much sense to punish spelling IMHO, but the person who wrote "desoxyribonucliec acid" probably meant the correct thing in a larger context and should get full score. It's not a dictation.
